### ISSUE TITLE
Sinnvolle Funktionen auf andere AddOns verteilen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/xcore#3]
Sollte man sinnvolles aus Xcore nicht auf bestehende AddOns verteilen?

**Comment by skerbis** [comment]
Aktuell ist das AddOn sehr hilfreich bei einer Konvertierung von REDAXO 4.x zu REDAXO 5.x. 
Man könnte ggf. auch darüber nachdenken Funktionen hier zu entfernen die bereits durch andere AddOns ersetzt wurden.  (Was aber eine spätere Konvertierung von REX4 zu REX5 erschweren würde).

**Comment by tbaddade** [comment]
Ich schließe. Falls noch von Interesse gern wieder öffnen.
