### ISSUE TITLE
Class rexx umbenennen 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/xcore#5]
Die Bezeichnung erweckt auf den ersten Blick den Eindruck es handele sich um eine Core- Class

**Comment by skerbis** [comment]
Meinungen? @staabm @gharlan @alexplusde  ?

**Comment by AWqxKAWERbXo** [comment]
Das war sicher bewusst, um möglichst viel getippsel zu sparen. Ich würde die fragen, die das nutzen, und darauf achten, dass keine Rückwärtskompatibilität verhindert wird.

Es stört ja niemanden, oder?

**Comment by staabm** [comment]
Ich hab da keine Meinung dazu

**Comment by skerbis** [comment]
Na dann, bleibts so

**Comment by fietstouring** [comment]
ja bitte Rückwärtskompatibilität beachten! Danke.
