### ISSUE TITLE
LangPreset 'en' wird durch 'de' ersetzt

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/xcore#7]
Auf einem Redaxo 5.8 mit nur einer Sprache 'english' (Code: 'en') werden meistens die richtigen URLs generiert ('&' wird durch 'and' ersetzt). Aber immer mal wieder (unregelmäßig) sind die URLs falsch ('&' wird durch 'und' ersetzt). Durchs Neuinstallieren von Yrewrite lässt sich das Problem beheben, aber das ist nur ein Workaround.

**Comment by skerbis** [comment]
yrewrite_scheme benutzen und Beispiel "Schema modifizieren" anschauen.
